
apiVersion: v1
kind: Secret
metadata:
  name: jfrog-art-cred
  namespace: sameera
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJzYW1lZXJhNzI2OC5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiWkc5amEyVnlMV055WldRNlVHOXZhbWwwYUdGQVpHRmthVFE9IgoJCX0KCX0KfQ==

type: kubernetes.io/dockerconfigjson
